### ISSUE TITLE
How to configure CMakeLists to use VS Code to build the package internally.

### ISSUE THREAD

**Issue by JulianCeaser** [osquery/osquery-packaging#12]
Right now it is quite easy to use VS Code to build the original Osquery package.

However there are a number of manual steps that need to be done in order to get the osquery_packaging done and I am not sure how to get them done via CMakeLists or VS Code.

Things like settings DESTDIR, OSQUERY_VERSION, OSQUERY_DATA_PATH, CPACK_GENERATOR, OSQUERY_BITNESS need to be set manually or as part of environment variables.

Any way to set them in CMakeLists to be able to use them in VS Code directly? 

The documentation is too focused on building all of it from the command line.

**Comment by Smjert** [comment]
Hello @JulianCeaser,
Everything you mentioned except for DESTDIR is a CMake option that can be configured (and saved for next configures) in the VSCode CMake extension settings (`Cmake: Configure Args` specifically), as you would do for instance for enabling the tests.

DESTDIR too can be set as an environment variable in VSCode that's active when creating the intermediate package from `osquery/osquery`; it can be set in `Cmake: Build Environment` when using `cmake --build . --target install`.

**Comment by JulianCeaser** [comment]
> Hello @JulianCeaser,
> Everything you mentioned except for DESTDIR is a CMake option that can be configured (and saved for next configures) in the VSCode CMake extension settings (`Cmake: Configure Args` specifically), as you would do for instance for enabling the tests.
> 
> DESTDIR too can be set as an environment variable in VSCode that's active when creating the intermediate package from `osquery/osquery`; it can be set in `Cmake: Build Environment` when using `cmake --build . --target install`.

Okay I will try these things, I do not use the console when using VSCode though, so `cmake --build . --target install` should be done through the VSCode terminal you mean ?

Also what is the base folder I should open for CMake so I can both create the ALL build as well as the package build ? 
Seems I need to manually delete the CMakeCache file each time and re-configure by changing the source directory manually.
Unsure how to get it done with the VSCode CMake Extension GUI.

**Comment by Smjert** [comment]
>Okay I will try these things, I do not use the console when using VSCode though, so cmake --build . --target install should be done through the VSCode terminal you mean ?

Sorry, what I meant here is that you can set in VSCode that environment variable so that it's picked up when you build the `install` target from VSCode.
If you have the CMake extension installed, on the bottom bar where you select the compiler, build type etc you can also select the target you want to build.
So any `target` we use from command line (`install`, `package`, `osqueryd` etc) can be used via VSCode.

>Also what is the base folder I should open for CMake so I can both create the ALL build as well as the package build ?
Seems I need to manually delete the CMakeCache file each time and re-configure by changing the source directory manually.
Unsure how to get it done with the VSCode CMake Extension GUI.

For opening multiple projects in the same VSCode instance (which I think it's what you're asking), admittedly I've never done that. Normally I just open two separate instances because each folder/project needs a slightly different configuration of the CMake extension and the CMake extension minimum granularity is the entire workspace (afaik).

But I see you can open multiple folder: https://code.visualstudio.com/docs/editor/multi-root-workspaces, although I suspect that in this case you will still have a single configuration for the whole workspace which is problematic, because you need a different CMake config for each folder, as I was saying previously.

**Comment by JulianCeaser** [comment]
I tried to add the configure args like this but the environment variables don't seem to be resolving properly.

![image](https://user-images.githubusercontent.com/14332771/130983808-4eefaa16-4342-48c4-8a75-dd5b164c106b.png)
![image](https://user-images.githubusercontent.com/14332771/130983883-b17c8b37-7f9a-4424-9087-7f1a141f344b.png)

What do I need to do instead ?

**Comment by Smjert** [comment]
> What do I need to do instead ?

I'm not sure if that's the issue but beware that the `Configure args` parameters need also the `-D` switch so that they are actually recognized as CMake options.
So `-DCPACK_GENERATOR=WIX`.

Though I think the Configure Environment is meant to pass env vars to the CMake process itself during configuration, while there you're expecting the parent process, calling CMake, to expand the variable on the CLI, which is different.
Given that you're still saving the env var value in vscode, so it's not dynamic, why not just passing the correct value directly in the Configure Args?

For `DESTDIR` though, Configure Environment is the correct use.

EDIT:
A further thought, it seems like those configure args you're passing are for the `osquery-packaging` repository, but then you're also setting a `DESTIDIR` env var and reusing it in the configure args.
I think this is partially what I was saying earlier about the CMake configuration needing to be different between the `osquery/osquery` and `osquery/osquery-packaging` repositories.
`DESTDIR` is only used in `osquery/osquery` to direct CMake and the logic of the `install` target, it's not used anymore in the `osquery/osquery-packaging` repository.

**Comment by JulianCeaser** [comment]
Okay understood. So to summarize, here is what is needed
1. Make two VS Code folder windows so that they do not obstruct one another.

2. For the main **osquery** build, the **DESTDIR** needs to set as an **Cmake: Build Environment** variable that has the absolute path.
![image](https://user-images.githubusercontent.com/14332771/131081751-6c498303-139a-42e0-8bab-49694d77bad3.png)

3. For the secondary **osquery-packaging** build, the following must be set explicitly without using any build Configure Environment variable, since VS Code will not automatically expand those during configuration. So it needs to be manually updated every time. Here is what worked for me.
Edit: I guess the **Cmake: Configure Environment** variables don't serve any purpose at all and can be removed.
![image](https://user-images.githubusercontent.com/14332771/131081456-70f7ec49-b931-4627-9e92-e2e8726e5634.png)

4. Finally for the **osquery-packaging** build there is no **package** target in the VSCode, so I needed to open the terminal to type in the `cmake --build .\build\ --target package` to get it to build. If someone could add the package target or guide me on how to add it myself it would be great.
![image](https://user-images.githubusercontent.com/14332771/131081675-40c89535-fafe-4932-89e4-5e906136f0e5.png)


**EDIT 2**: Lastly, the VSCode Cmake extension settings seem to be common for both the packaging. Does that mean these seem argument will be applying to all future projects I work on. Does not seem to be project specific right now when using VS Code.

**Comment by Smjert** [comment]
I realized I said that `DESTDIR` was correct under Configure Environment, but indeed it's the Build Environment the correct one.
Configure Environment is to set env vars that CMake logic can read at configure time (via `$ENV{VAR}`), but we are not using that.

As for 4., I will double check, but it might be that CPack is not creating a real target, so this is a limit of CMake/CPack.

Finally, for your last edit, vscode settings have a context, which can be chosen on the top left of the settings page. You should have at least User and Workspace, where User is global for all projects, and Workspace is for the current workspace you're using (which should be your osquery folder); you want to use Workspace.

**Comment by Smjert** [comment]
I'm considering this as addressed for now. Consider joining our Slack with this [link](https://join.slack.com/t/osquery/shared_invite/zt-h29zm0gk-s2DBtGUTW4CFel0f0IjTEw) if you have further questions
